import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import fs from 'node:fs';

const dbPath = '/tmp/openboots-vitest.db';
try { fs.rmSync(dbPath); } catch {}
process.env.NODE_ENV = 'test'; process.env.DATABASE_PATH = dbPath; process.env.JWT_SECRET = 'test-secret'; process.env.CORE_MODE = 'demo';
const { app } = await import('../server.js');
const { deliveryNoteText, parseLabelText, viberPreview } = await import('../services.js');
const { db } = await import('../db.js');

let server: any; let base = ''; let cookie = '';
async function request(path: string, init: RequestInit = {}) { const response = await fetch(`${base}${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(init.headers || {}) } }); const set = response.headers.get('set-cookie'); if (set) cookie = set.split(';')[0]; const body = response.headers.get('content-type')?.includes('application/json') ? await response.json() : await response.arrayBuffer(); return { response, body }; }
const postJson = (path:string, data:any, headers?:HeadersInit) => request(path,{method:'POST',body:JSON.stringify(data),headers:{Cookie:cookie,...headers}});
const getJson = (path:string) => request(path,{headers:{Cookie:cookie}});

beforeAll(async()=>{server=app.listen(0);await new Promise<void>(resolve=>server.once('listening',()=>resolve()));base=`http://127.0.0.1:${server.address().port}`;const login=await request('/api/auth/login',{method:'POST',body:JSON.stringify({username:'admin',password:'admin'})});expect(login.response.status).toBe(200);});
afterAll(()=>{server.close();db.close();});

describe('OpenBoots critical workflows',()=>{
  it('scans known and unknown barcodes without duplicates',async()=>{const known=await postJson('/api/scan',{barcode:'1234567890123'});expect(known.response.status).toBe(200);expect(known.body.product.id).toBe(1);const unknown=await postJson('/api/scan',{barcode:'9999999999999'});expect(unknown.response.status).toBe(404);expect(unknown.body.error).toBe('UNKNOWN_BARCODE');const created=await postJson('/api/products',{name:'Test Shoe',brand:'Test',article:'T-1',barcode:'9999999999999',sizes:[{size:'40',quantity:1}],pairsPerBox:1,salePrice:10});expect(created.response.status).toBe(201);const duplicate=await postJson('/api/products',{name:'Duplicate',barcode:'9999999999999'});expect(duplicate.response.status).toBe(400);const linked=await postJson('/api/products/1/link-barcode',{barcode:'8888888888888'});expect(linked.response.status).toBe(200);const alias=await postJson('/api/scan',{barcode:'8888888888888'});expect(alias.body.product.id).toBe(1);});
  it('receives repeated and bulk quantities and undoes latest event',async()=>{const session=(await postJson('/api/receiving/sessions',{locationId:1})).body.session;const before=(await getJson('/api/products/1')).body.product.stock.find((x:any)=>x.location_id===1).quantity;await postJson(`/api/receiving/sessions/${session.id}/scan`,{barcode:'1234567890123'},{'Idempotency-Key':'receive-1'});await postJson(`/api/receiving/sessions/${session.id}/scan`,{barcode:'1234567890123'},{'Idempotency-Key':'receive-2'});await postJson(`/api/receiving/sessions/${session.id}/quantity`,{barcode:'1234567890123',quantity:20},{'Idempotency-Key':'receive-bulk'});const duplicate=await postJson(`/api/receiving/sessions/${session.id}/quantity`,{barcode:'1234567890123',quantity:20},{'Idempotency-Key':'receive-bulk'});expect(duplicate.body.quantity).toBe(20);const after=(await getJson('/api/products/1')).body.product.stock.find((x:any)=>x.location_id===1).quantity;expect(after-before).toBe(22);await postJson(`/api/receiving/sessions/${session.id}/undo`,{});const undone=(await getJson('/api/products/1')).body.product.stock.find((x:any)=>x.location_id===1).quantity;expect(undone).toBe(after-20);});
  it('transfers atomically and rejects insufficient stock',async()=>{const before=(await getJson('/api/products/1')).body.product.stock;const result=await postJson('/api/transfers',{fromLocationId:1,toLocationId:2,lines:[{productId:1,quantity:3}]},{'Idempotency-Key':'transfer-1'});const duplicate=await postJson('/api/transfers',{fromLocationId:1,toLocationId:2,lines:[{productId:1,quantity:3}]},{'Idempotency-Key':'transfer-1'});expect(result.response.status).toBe(200);expect(duplicate.response.status).toBe(200);const after=(await getJson('/api/products/1')).body.product.stock;expect(after.find((x:any)=>x.location_id===1).quantity).toBe(before.find((x:any)=>x.location_id===1).quantity-3);expect(after.find((x:any)=>x.location_id===2).quantity).toBe(before.find((x:any)=>x.location_id===2).quantity+3);const failed=await postJson('/api/transfers',{fromLocationId:1,toLocationId:2,lines:[{productId:1,quantity:99999}]});expect(failed.response.status).toBe(409);});
  it('keeps order draft, confirms once, and returns idempotent result',async()=>{const order=(await postJson('/api/orders',{name:'Alexander',phone:'+380501112233',sourceLocationId:1})).body.order;await postJson(`/api/orders/${order.id}/scan`,{barcode:'1234567890123'});await postJson(`/api/orders/${order.id}/scan`,{barcode:'1234567890123'});const draft=(await getJson(`/api/orders/${order.id}`)).body.order;expect(draft.status).toBe('DRAFT');const stockBefore=(await getJson('/api/products/1')).body.product.stock.find((x:any)=>x.location_id===1).quantity;const first=await postJson(`/api/orders/${order.id}/confirm`,{}, {'Idempotency-Key':'test-confirm-1'});const second=await postJson(`/api/orders/${order.id}/confirm`,{}, {'Idempotency-Key':'test-confirm-1'});expect(first.response.status).toBe(200);expect(first.body.order.status).toBe('CONFIRMED');expect(second.body.order.delivery_number).toBe(first.body.order.delivery_number);const stockAfter=(await getJson('/api/products/1')).body.product.stock.find((x:any)=>x.location_id===1).quantity;expect(stockBefore-stockAfter).toBe(2);});
  it('keeps order draft, confirms once, and returns idempotent result',async()=>{const order=(await postJson('/api/orders',{name:'Alexander',phone:'+380501112233',sourceLocationId:1})).body.order;await postJson(`/api/orders/${order.id}/scan`,{barcode:'1234567890123'});await postJson(`/api/orders/${order.id}/scan`,{barcode:'1234567890123'});const draft=(await getJson(`/api/orders/${order.id}`)).body.order;expect(draft.status).toBe('DRAFT');const stockBefore=(await getJson('/api/products/1')).body.product.stock.find((x:any)=>x.location_id===1).quantity;const first=await postJson(`/api/orders/${order.id}/confirm`,{}, {'Idempotency-Key':'test-confirm-1'});const second=await postJson(`/api/orders/${order.id}/confirm`,{}, {'Idempotency-Key':'test-confirm-1'});expect(first.response.status).toBe(200);expect(first.body.order.status).toBe('CONFIRMED');expect(second.body.order.delivery_number).toBe(first.body.order.delivery_number);const stockAfter=(await getJson('/api/products/1')).body.product.stock.find((x:any)=>x.location_id===1).quantity;expect(stockBefore-stockAfter).toBe(2);const emptyOrder=(await postJson('/api/orders',{name:'No Stock',phone:'+380501112244',sourceLocationId:1})).body.order;await postJson(`/api/orders/${emptyOrder.id}/scan`,{barcode:'9999999999999'});const insufficient=await postJson(`/api/orders/${emptyOrder.id}/confirm`,{}, {'Idempotency-Key':'test-insufficient'});expect(insufficient.response.status).toBe(409);});
  it('creates price-free delivery note and priced Viber preview',async()=>{const order=(await getJson('/api/orders/1')).body.order;const pdf=await getJson(`/api/orders/${order.id}/delivery-note.pdf`);expect(pdf.response.status).toBe(200);const raw=Buffer.from(pdf.body);expect(raw.subarray(0,5).toString()).toBe('%PDF-');const note=deliveryNoteText(order);expect(note).not.toContain('1250');expect(note).not.toContain('Ціна');const preview=viberPreview((await getJson('/api/products/1')).body.product);expect(preview).toContain('Ціна:');expect(preview).toContain('1 250');});
  it('searches customers, filters stock, renders labels, and applies reviewed counts',async()=>{const customers=await getJson('/api/customers?query=%2B380501112233');expect(customers.body.customers[0].phone).toBe('+380501112233');const filtered=await getJson('/api/products?brand=New%20Balance&locationId=1&inStock=true');expect(filtered.body.products[0].brand).toBe('New Balance');const label=await getJson('/api/products/1/label');expect(label.response.status).toBe(200);expect(new TextDecoder().decode(label.body)).toContain('INV-000001824');const count=(await postJson('/api/counts',{locationId:1})).body.count;const line=count.lines.find((x:any)=>x.product_id===1);await postJson(`/api/counts/${count.id}/lines`,{productId:1,actual:line.expected+1});const applied=await postJson(`/api/counts/${count.id}/apply`,{});expect(applied.body.count.status).toBe('APPLIED');});
});

describe('OCR and Viber deterministic boundaries',()=>{it('parses partial labels safely and keeps fields editable',()=>{const parsed=parseLabelText('ART: B7201\nCOLOR: BLACK\nSIZES: 36 x 1\n37 x 2\nQTY: 3');expect(parsed.article).toBe('B7201');expect(parsed.color).toBe('BLACK');expect(parsed.sizes).toHaveLength(1);expect(parsed.pairsPerBox).toBe(3);expect(parsed.rawText).toContain('ART:');});it('requires price before Viber publication',()=>{expect(()=>viberPreview({name:'No Price',sizes:[]} as any)).toThrow('PRICE_REQUIRED');});});
