import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';
import jwt from 'jsonwebtoken';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import { z } from 'zod';
import { db, passwordHash, timestamp, tx } from './db.js';
import { core } from './core.js';
import { inventreeConfigured, InvenTreeInventoryCore } from './inventree.js';
import { makeDeliveryPdf, makeLabelHtml, officialViberPublish, parseLabelText, recognizeImage, viberPreview } from './services.js';

const app = express(); const port = Number(process.env.PORT || 3000); const jwtSecret = process.env.JWT_SECRET || 'dev-only-change-me'; if (process.env.NODE_ENV === 'production' && jwtSecret === 'dev-only-change-me') throw new Error('JWT_SECRET must be configured in production'); const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024 } });
app.use(helmet({ contentSecurityPolicy: false })); app.use(cors({ origin: ['http://localhost:5173', 'http://localhost:3000'], credentials: true })); app.use(express.json({ limit: '1mb' })); app.use(cookieParser()); app.use('/api', rateLimit({ windowMs: 60 * 1000, limit: 240, standardHeaders: true, legacyHeaders: false }));

const issueToken = (user) => jwt.sign({ sub: user.id, username: user.username, role: user.role }, jwtSecret, { expiresIn: '12h' });
const auth = (req, res, next) => { try { const token = req.cookies.openboots_session || req.headers.authorization?.replace(/^Bearer /, ''); if (!token) return res.status(401).json({ error: 'AUTH_REQUIRED', message: 'Войдите в систему.' }); req.user = jwt.verify(token, jwtSecret); next(); } catch { return res.status(401).json({ error: 'AUTH_REQUIRED', message: 'Сессия истекла. Войдите снова.' }); } };
const validate = (schema) => (req, res, next) => { const result=schema.safeParse(req.body); if(!result.success)return res.status(400).json({error:'VALIDATION_ERROR',message:'Проверьте заполненные поля.',details:result.error.flatten()}); req.body=result.data; next(); };
const safeError = (error, res) => { const map={INSUFFICIENT_STOCK:['INSUFFICIENT_STOCK','Недостаточно товара на складе.'],DUPLICATE_BARCODE:['DUPLICATE_BARCODE','Этот штрихкод уже привязан к товару.'],UNKNOWN_BARCODE:['UNKNOWN_BARCODE','Штрихкод не найден.'],PRICE_REQUIRED:['PRICE_REQUIRED','Укажите цену товара перед публикацией.'],EMPTY_ORDER:['EMPTY_ORDER','Добавьте товар в заказ.'],ORDER_NOT_DRAFT:['ORDER_NOT_DRAFT','Заказ уже закрыт и не может быть изменён.'],INVENTREE_NOT_CONFIGURED:['CORE_NOT_CONFIGURED','Inventory core не настроен для production.']}; const [code,message]=map[error.code]||['OPERATION_FAILED','Операция не выполнена. Попробуйте ещё раз.']; console.error(`[${code}]`, error.message); return res.status(code==='INSUFFICIENT_STOCK'?409:400).json({error:code,message}); };
const productPayload = z.object({ name:z.string().min(1), brand:z.string().optional(), model:z.string().optional(), article:z.string().optional(), color:z.string().optional(), sizes:z.array(z.object({size:z.string().min(1),quantity:z.number().int().positive()})).optional(), pairsPerBox:z.number().int().positive().nullable().optional(), salePrice:z.number().nonnegative().nullable().optional(), barcode:z.string().trim().optional(), internalBarcode:z.string().trim().optional(), note:z.string().optional() });

app.post('/api/auth/login', validate(z.object({ username:z.string().min(1), password:z.string().min(1) })), (req,res)=> { const user=db.prepare('SELECT * FROM users WHERE username=?').get(req.body.username); if(!user || passwordHash(req.body.password)!==user.password_hash)return res.status(401).json({error:'INVALID_LOGIN',message:'Неверный логин или пароль.'}); res.cookie('openboots_session',issueToken(user),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:12*60*60*1000}); res.json({user:{id:user.id,username:user.username,role:user.role}}); });
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('openboots_session');res.json({ok:true});}); app.get('/api/me',auth,(req,res)=>res.json({user:req.user,mode:process.env.CORE_MODE||'demo',inventreeConfigured}));
app.get('/api/health',(req,res)=>res.json({ok:true,mode:process.env.CORE_MODE||'demo',inventreeConfigured}));

app.get('/api/locations',auth,(req,res)=>res.json({locations:core.getLocations()}));
app.get('/api/products',auth,(req,res)=>res.json({products:core.searchProducts(String(req.query.query||''),{inStock:req.query.inStock==='true',brand:req.query.brand,color:req.query.color,size:req.query.size,locationId:req.query.locationId})}));
app.get('/api/products/:id',auth,(req,res)=>{const p=core.getProduct(Number(req.params.id));if(!p)return res.status(404).json({error:'NOT_FOUND',message:'Товар не найден.'});res.json({product:{...p,stock:core.getStock(p.id),movements:core.getMovementHistory(p.id)}});});
app.post('/api/products',auth,validate(productPayload),(req,res)=>{try{res.status(201).json({product:core.createProduct(req.body)});}catch(e){safeError(e,res);}});
app.post('/api/products/:id/link-barcode',auth,validate(z.object({barcode:z.string().min(4)})),(req,res)=>{try{res.json({product:core.linkBarcode(Number(req.params.id),req.body.barcode)});}catch(e){safeError(e,res);}});

app.post('/api/scan',auth,validate(z.object({barcode:z.string().trim().min(4)})),(req,res)=>{const product=core.findProductByBarcode(req.body.barcode);if(!product)return res.status(404).json({error:'UNKNOWN_BARCODE',message:'Штрихкод не найден.',barcode:req.body.barcode});res.json({product,stock:core.getStock(product.id)});});
app.post('/api/receiving/sessions',auth,validate(z.object({locationId:z.number().int().positive()})),(req,res)=>{try{const r=db.prepare('INSERT INTO receiving_sessions(location_id,created_at) VALUES (?,?)').run(req.body.locationId,timestamp());res.status(201).json({session:{id:r.lastInsertRowid,locationId:req.body.locationId,status:'OPEN',events:[]}});}catch(e){safeError(e,res);}});
const receiveScan = (req,res,quantity=1) => { try { const session=db.prepare("SELECT * FROM receiving_sessions WHERE id=? AND status='OPEN'").get(Number(req.params.id)); if(!session)throw new Error('SESSION_CLOSED'); const key=req.headers['idempotency-key']; const previous=key&&db.prepare('SELECT response_json FROM idempotency WHERE scope=? AND key=?').get(`receive:${session.id}`,String(key)); if(previous)return res.json(JSON.parse(previous.response_json)); const product=core.findProductByBarcode(req.body.barcode); if(!product) return res.status(404).json({error:'UNKNOWN_BARCODE',message:'Штрихкод не найден.',barcode:req.body.barcode}); const response=tx(()=>{core.mutateStock(product.id,session.location_id,quantity,'RECEIVE',String(session.id),req.user.sub);db.prepare('INSERT INTO receiving_events(session_id,product_id,quantity,barcode,created_at) VALUES (?,?,?,?,?)').run(session.id,product.id,quantity,req.body.barcode,timestamp());const result={product,barcode:req.body.barcode,quantity,stock:core.getStock(product.id),sessionId:session.id};if(key)db.prepare('INSERT INTO idempotency(scope,key,response_json,created_at) VALUES (?,?,?,?)').run(`receive:${session.id}`,String(key),JSON.stringify(result),timestamp());return result;}); res.json(response); }catch(e){safeError(e,res);} };
app.post('/api/receiving/sessions/:id/scan',auth,validate(z.object({barcode:z.string().trim().min(4)})),(req,res)=>receiveScan(req,res));
app.post('/api/receiving/sessions/:id/quantity',auth,validate(z.object({barcode:z.string().trim().min(4),quantity:z.number().int().positive().max(10000)})),(req,res)=>receiveScan(req,res,req.body.quantity));
app.post('/api/receiving/sessions/:id/undo',auth,(req,res)=>{try{const event=db.prepare('SELECT * FROM receiving_events WHERE session_id=? ORDER BY id DESC LIMIT 1').get(Number(req.params.id));if(!event)return res.status(400).json({error:'NOTHING_TO_UNDO',message:'Нечего отменять.'});const session=db.prepare("SELECT * FROM receiving_sessions WHERE id=? AND status='OPEN'").get(event.session_id);if(!session)throw new Error('SESSION_CLOSED');const result=tx(()=>{core.mutateStock(event.product_id,session.location_id,-event.quantity,'RECEIVE_UNDO',String(session.id),req.user.sub);db.prepare('DELETE FROM receiving_events WHERE id=?').run(event.id);return core.getStock(event.product_id);});res.json({ok:true,product:core.getProduct(event.product_id),quantity:event.quantity,stock:result});}catch(e){safeError(e,res);}});
app.post('/api/receiving/sessions/:id/complete',auth,(req,res)=>{db.prepare("UPDATE receiving_sessions SET status='COMPLETED' WHERE id=? AND status='OPEN'").run(Number(req.params.id));res.json({ok:true});});

app.post('/api/transfers',auth,validate(z.object({fromLocationId:z.number().int().positive(),toLocationId:z.number().int().positive(),lines:z.array(z.object({productId:z.number().int().positive(),quantity:z.number().int().positive()})).min(1)})),(req,res)=>{if(req.body.fromLocationId===req.body.toLocationId)return res.status(400).json({error:'SAME_LOCATION',message:'Выберите разные места.'});try{const key=req.headers['idempotency-key'];if(key){const previous=db.prepare('SELECT response_json FROM idempotency WHERE scope=? AND key=?').get('transfer',String(key));if(previous)return res.json(JSON.parse(previous.response_json));}const response=tx(()=>{core.transfer(req.body.lines,req.body.fromLocationId,req.body.toLocationId,crypto.randomUUID(),req.user.sub);const result={ok:true};if(key)db.prepare('INSERT INTO idempotency(scope,key,response_json,created_at) VALUES (?,?,?,?)').run('transfer',String(key),JSON.stringify(result),timestamp());return result;});res.json(response);}catch(e){safeError(e,res);}});

app.get('/api/customers',auth,(req,res)=>res.json({customers:core.searchCustomers(String(req.query.query||''))})); app.post('/api/customers',auth,validate(z.object({name:z.string().min(1),phone:z.string().min(5),note:z.string().optional()})),(req,res)=>{try{res.status(201).json({customer:core.createCustomer(req.body)});}catch(e){safeError(e,res);}});
app.post('/api/orders',auth,validate(z.object({customerId:z.number().int().positive().optional(),name:z.string().min(1).optional(),phone:z.string().min(5).optional(),sourceLocationId:z.number().int().positive(),note:z.string().optional()})),(req,res)=>{try{res.status(201).json({order:core.createOrder(req.body)});}catch(e){safeError(e,res);}});
app.get('/api/orders/:id',auth,(req,res)=>{const order=core.getOrder(Number(req.params.id));if(!order)return res.status(404).json({error:'NOT_FOUND',message:'Заказ не найден.'});res.json({order});});
app.post('/api/orders/:id/scan',auth,validate(z.object({barcode:z.string().trim().min(4)})),(req,res)=>{try{const p=core.findProductByBarcode(req.body.barcode);if(!p)return res.status(404).json({error:'UNKNOWN_BARCODE',message:'Штрихкод не найден.',barcode:req.body.barcode});res.json({order:core.addOrderLine(Number(req.params.id),p.id,1),product:p});}catch(e){safeError(e,res);}});
app.post('/api/orders/:id/confirm',auth,(req,res)=>{try{const key=req.headers['idempotency-key']||crypto.randomUUID();res.json({order:core.confirmOrder(Number(req.params.id),String(key),req.user.sub)});}catch(e){safeError(e,res);}}); app.post('/api/orders/:id/cancel',auth,(req,res)=>res.json({order:core.cancelOrder(Number(req.params.id))}));
app.get('/api/orders/:id/delivery-note.pdf',auth,(req,res)=>{const order=core.getOrder(Number(req.params.id));if(!order||order.status!=='CONFIRMED')return res.status(400).json({error:'NOT_CONFIRMED',message:'Сначала подтвердите продажу.'});makeDeliveryPdf(order,res);});
app.get('/api/products/:id/label',auth,async(req,res)=>{try{const p=core.getProduct(Number(req.params.id));if(!p)return res.status(404).send('Not found');res.type('html').send(await makeLabelHtml(p));}catch(e){safeError(e,res);}});
app.get('/api/products/:id/movements',auth,(req,res)=>res.json({movements:core.getMovementHistory(Number(req.params.id))}));

app.post('/api/ocr/parse',auth,validate(z.object({text:z.string()})),(req,res)=>res.json({fields:parseLabelText(req.body.text)}));
app.post('/api/ocr/recognize',auth,upload.single('image'),async(req,res)=>{try{if(!req.file && !req.body.text)return res.status(400).json({error:'IMAGE_REQUIRED',message:'Добавьте фото этикетки.'});const result=req.file?await recognizeImage(req.file.buffer):{text:req.body.text,confidence:1};res.json({...result,fields:parseLabelText(result.text)});}catch(e){safeError(e,res);}});
app.post('/api/viber/preview',auth,validate(productPayload),(req,res)=>{try{res.json({message:viberPreview(req.body)});}catch(e){safeError(e,res);}});
app.post('/api/viber/publish',auth,validate(z.object({message:z.string().min(1)})),async(req,res)=>{try{res.json(await officialViberPublish(req.body.message));}catch(e){safeError(e,res);}});
app.post('/api/counts',auth,validate(z.object({locationId:z.number().int().positive()})),(req,res)=>res.status(201).json({count:core.beginCount(req.body.locationId)})); app.get('/api/counts/:id',auth,(req,res)=>res.json({count:core.getCount(Number(req.params.id))})); app.post('/api/counts/:id/lines',auth,validate(z.object({productId:z.number().int().positive(),actual:z.number().int().nonnegative()})),(req,res)=>res.json({count:core.updateCountLine(Number(req.params.id),req.body.productId,req.body.actual)})); app.post('/api/counts/:id/apply',auth,(req,res)=>{try{res.json({count:core.applyCount(Number(req.params.id),req.user.sub)});}catch(e){safeError(e,res);}});

const publicDir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../dist'); app.use(express.static(publicDir)); app.get(/^(?!\/api).*/, (req,res,next)=>res.sendFile(path.join(publicDir,'index.html'), (error)=>error?next():undefined)); app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'SERVER_ERROR',message:'Внутренняя ошибка сервера.'});});
if (process.env.NODE_ENV !== 'test') app.listen(port,()=>console.log(`OpenBoots server listening on http://localhost:${port}`));
export { app };
